### ISSUE TITLE
Missing characters from Table of General Standard Chinese Characters

### ISSUE THREAD

**Issue by tatzelbrumm** [SolidZORO/zpix-pixel-font#9]
I am using the [Table of General Standard Chinese Characters](http://hanzidb.org/character-list/general-standard) to select characters from the zpix font according to the [unicode mapping table](http://hanzidb.org/TGSCC-Unicode.txt). 
Most of the 8105 characters in the TGSCC table are in the zpix font, but 276 characters are missing, see
[missingTGSCCcodes_utf8.txt](https://github.com/SolidZORO/zpix-pixel-font/files/1936062/missingTGSCCcodes_utf8.txt). 

- Have you defined these characters elsewhere in your space of 22000+ characters?
- If not, are you planning to add the missing glyphs?
- If neither, what would be the best way to add the missing glyphs? 

As a Westerner who is illiterate in Chinese, I don't know how to simplify the characters for a 12x12 pixel display.

**Comment by SolidZORO** [comment]
sorry, the answer is too late.

Q: Have you defined these characters elsewhere in your space of 22000+ characters?
A: not.

Q: If not, are you planning to add the missing glyphs?
A:  i have not plan now. because work busy : (

Q: If neither, what would be the best way to add the missing glyphs?
A: you can install https://github.com/fontforge/fontforge and open Zpix.bdf, edit and done.
